version: '3.9'

services:
  frontend:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WDS_SOCKET_PORT=3000
      - REACT_APP_DOMAIN=${REACT_APP_DOMAIN}
      - REACT_APP_IMAGE_PREFIX=${REACT_APP_IMAGE_PREFIX}
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - react-network

networks:
  react-network:
    driver: bridge